import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#486648',
        'primary-container': '#9ebf9c',
        'primary-fixed': '#c9ecc6',
        'primary-fixed-dim': '#aecfab',
        'on-primary': '#ffffff',
        'on-primary-container': '#314e33',
        'on-primary-fixed': '#04210a',
        'secondary': '#4c644e',
        'secondary-container': '#ceeacd',
        'secondary-fixed': '#ceeacd',
        'secondary-fixed-dim': '#b3ceb2',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#526a53',
        'tertiary': '#556257',
        'tertiary-container': '#acbaad',
        'tertiary-fixed': '#d8e6d8',
        'tertiary-fixed-dim': '#bccabd',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#3e4b40',
        'surface': '#f8faf8',
        'surface-dim': '#d8dad9',
        'surface-bright': '#f8faf8',
        'surface-variant': '#e1e3e1',
        'surface-tint': '#486648',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f2',
        'surface-container': '#eceeec',
        'surface-container-high': '#e6e9e7',
        'surface-container-highest': '#e1e3e1',
        'on-surface': '#191c1b',
        'on-surface-variant': '#424841',
        'outline': '#737971',
        'outline-variant': '#c2c8bf',
        'background': '#f8faf8',
        'on-background': '#191c1b',
        'inverse-surface': '#2e3130',
        'inverse-on-surface': '#eff1ef',
        'inverse-primary': '#aecfab',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        'headline': ['Noto Serif', 'Georgia', 'serif'],
        'body': ['Manrope', 'sans-serif'],
        'label': ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      keyframes: {
        orbit: {
          '0%': { transform: 'rotate(0deg) translateX(120px) rotate(0deg)' },
          '100%': { transform: 'rotate(360deg) translateX(120px) rotate(-360deg)' },
        },
        'orbit-reverse': {
          '0%': { transform: 'rotate(0deg) translateX(160px) rotate(0deg)' },
          '100%': { transform: 'rotate(-360deg) translateX(160px) rotate(360deg)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '33%': { transform: 'translateY(-12px) rotate(1deg)' },
          '66%': { transform: 'translateY(-6px) rotate(-1deg)' },
        },
        'spin-slow': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'border-spin': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'film-scroll': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        particle: {
          '0%': { transform: 'translateY(100vh) rotate(0deg)', opacity: '0' },
          '10%': { opacity: '1' },
          '90%': { opacity: '0.5' },
          '100%': { transform: 'translateY(-100px) rotate(720deg)', opacity: '0' },
        },
      },
      animation: {
        'orbit': 'orbit 20s linear infinite',
        'orbit-reverse': 'orbit-reverse 28s linear infinite',
        'orbit-slow': 'orbit 35s linear infinite',
        'float': 'float 6s ease-in-out infinite',
        'float-delay': 'float 8s ease-in-out 2s infinite',
        'spin-slow': 'spin-slow 20s linear infinite',
        'border-spin': 'border-spin 4s linear infinite',
        'fade-up': 'fade-up 0.8s ease-out forwards',
        'film-scroll': 'film-scroll 30s linear infinite',
        'particle': 'particle 8s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}

export default config
