import { Memory, Friend, TimelineEvent } from '@/types'

export const FRIENDS: Friend[] = [
  {
    id: 'hammad-masood',
    name: 'hammad Masood',
    nickname: 'Quaid-e-Azam',
    quote: 'Every equation has a beautiful solution, just like every moment has meaning.',
    avatarColor: '#486648',
    initials: 'HM',
    memoriesCount: 0,
  },
  {
    id: 'Raza-khan',
    name: 'Raza Khan',
    nickname: 'Chacha',
    quote: 'Life is the art of drawing without an eraser. Cherish every stroke.',
    avatarColor: '#4c644e',
    initials: 'RK',
    memoriesCount: 0,
  },
  {
    id: 'hammad-shah',
    name: 'Hammad Shah',
    nickname: 'Hammad',
    quote: 'The best stories are the ones we live together.',
    avatarColor: '#556257',
    initials: 'HS',
    memoriesCount: 0,
  },
  {
    id: 'Aitzaz-hasan',
    name: 'Aitzaz Hasan',
    nickname: 'Pull Stack Dev',
    quote: 'Friendship is not a big thing — it\'s a million little things.',
    avatarColor: '#304d32',
    initials: 'AH',
    memoriesCount: 0,
  },
]

export const INITIAL_MEMORIES: Memory[] = [
  {
    id: 'mem-001',
    title: 'First Day at University',
    description: 'The day everything began. Four strangers walked into the same hall, not knowing they would become a family. The air smelled of new beginnings and nervous excitement. We found each other in the crowd and somehow, the crowd disappeared.',
    date: '2023-08-15',
    location: 'University Campus',
    imagePath: '/images/pic1.jpg',
    uploadedBy: 'hammad Masood',
    tags: ['beginning', 'university', 'milestone'],
    isPrivate: false,
    createdAt: '2023-08-15T10:00:00Z',
    series: 'Chapter One',
  },
  {
    id: 'mem-002',
    title: 'Whispers of the Tides',
    description: 'The sound of crashing waves and the warmth of the sand between our toes. Our first escape after the summer began. We drove without a map and arrived exactly where we needed to be.',
    date: '2023-09-10',
    location: 'Beach',
    imagePath: '/images/pic2.jpg',
    uploadedBy: 'Raza Khan',
    tags: ['beach', 'summer', 'adventure'],
    isPrivate: false,
    createdAt: '2023-09-10T14:00:00Z',
    series: 'Summer Series',
  },
  {
    id: 'mem-003',
    title: 'A Toast to Life',
    description: 'Candlelight, shared plates, and laughter that echoed into the cool winter night. Celebrating the milestone of a year well lived. The food was good but the company was extraordinary.',
    date: '2023-12-20',
    location: 'Old Town Restaurant',
    imagePath: '/images/pic3.jpg',
    uploadedBy: 'Hammad Shah',
    tags: ['celebration', 'birthday', 'winter'],
    isPrivate: false,
    createdAt: '2023-12-20T20:00:00Z',
    series: 'Celebrations',
  },
  {
    id: 'mem-004',
    title: 'Infinite Horizons',
    description: 'The open road stretched before us like a blank canvas. No destination, just the rhythm of the highway and the playlist of our lives. Sometimes the journey is more beautiful than any destination.',
    date: '2024-03-05',
    location: 'Mountain Highway',
    imagePath: '/images/pic4.jpeg',
    uploadedBy: 'Aitzaz Hasan',
    tags: ['road-trip', 'mountains', 'freedom'],
    isPrivate: false,
    createdAt: '2024-03-05T08:00:00Z',
    series: 'Adventures',
  },
  {
    id: 'mem-005',
    title: 'The Quiet Dock',
    description: 'A gathering of stillness beside the water. The lake reflected our faces back at us, calmer than we felt. Sometimes silence between friends is the loudest conversation.',
    date: '2024-09-04',
    location: 'Mountain Lake',
    imagePath: '/images/pic5.jpeg',
    uploadedBy: 'hammad Masood',
    tags: ['nature', 'lake', 'peace'],
    isPrivate: false,
    createdAt: '2024-09-04T17:00:00Z',
    series: 'Quiet Moments',
  },
  {
    id: 'mem-006',
    title: 'Ethereal Mornings',
    description: 'Fog rolling in over the fields as we walked without purpose. The kind of morning that makes you feel small in the most beautiful way possible. We talked about everything and nothing.',
    date: '2024-06-18',
    location: 'Countryside',
    imagePath: '/images/pic6.jpeg',
    uploadedBy: 'Raza Khan',
    tags: ['morning', 'fog', 'countryside'],
    isPrivate: false,
    createdAt: '2024-06-18T07:00:00Z',
    series: 'Quiet Moments',
  },
  {
    id: 'mem-007',
    title: 'Summer of \'25',
    description: 'The golden months, preserved in light and shadow. We had grown into ourselves and each other. The university years had given us not just knowledge, but each other.',
    date: '2025-07-20',
    location: 'City Park',
    imagePath: '/images/pic7.jpeg',
    uploadedBy: 'Hammad Shah',
    tags: ['summer', '2025', 'golden'],
    isPrivate: false,
    createdAt: '2025-07-20T15:00:00Z',
    series: 'Summer Series',
  },
  {
    id: 'mem-008',
    title: 'New Year, Same Four',
    description: 'Another year turned on its axis and still, we were here. Together. Some things change with the seasons, but not this. Not us. The countdown felt different this year — more grateful, less anxious.',
    date: '2025-01-01',
    location: 'Rooftop',
    imagePath: '/images/pic8.jpeg',
    uploadedBy: 'Aitzaz Hasan',
    tags: ['new-year', 'celebration', 'rooftop'],
    isPrivate: false,
    createdAt: '2025-01-01T00:00:00Z',
    series: 'Celebrations',
  },
]

export const TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: 'evt-start',
    title: 'Where It All Began',
    date: '2023-08-15',
    description: 'Four friends meet at university. The beginning of everything.',
    type: 'milestone',
    memoryId: 'mem-001',
  },
  {
    id: 'evt-beach',
    title: 'First Adventure',
    date: '2023-09-10',
    description: 'Our first trip outside the university walls.',
    type: 'memory',
    memoryId: 'mem-002',
  },
  {
    id: 'evt-year1',
    title: 'One Year Together',
    date: '2024-08-15',
    description: 'A full year of shared memories, laughter, and growth.',
    type: 'milestone',
  },
  {
    id: 'evt-road',
    title: 'The Great Road Trip',
    date: '2024-03-05',
    description: 'Windows down, playlist on, no destination.',
    type: 'memory',
    memoryId: 'mem-004',
  },
  {
    id: 'evt-year2',
    title: 'Two Years Strong',
    date: '2025-08-15',
    description: 'Still here. Still us.',
    type: 'milestone',
  },
  {
    id: 'evt-today',
    title: 'Three Years & Counting',
    date: '2026-08-15',
    description: 'The journey continues.',
    type: 'upcoming',
  },
]

export const UPCOMING_EVENTS = [
  {
    id: 'up-001',
    title: 'Stargazing Night',
    date: '2026-08-15',
    subtitle: 'August 15, 2026 — Anniversary',
    status: 'SAVE THE DATE',
  },
  {
    id: 'up-002',
    title: 'The Summer Retreat 2026',
    date: '2026-07-01',
    subtitle: 'Planning: July — Destination TBD',
    status: 'PLANNING',
  },
  {
    id: 'up-003',
    title: 'Milestone Celebration',
    date: '2026-08-15',
    subtitle: 'A gathering of all the souls who have made this journey possible.',
    status: 'SAVE THE DATE',
  },
]
